from .fetch_deezer import get_deezer_artist_id
from .fetch_spotify import get_spotify_artist_id
from .fetch_soundcloud import get_soundcloud_artist_id, get_soundcloud_artist
from .fetch_musicbrainz import find_artist_by_name
